module.exports = {
  // HTTP Status Codes
  ACCEPTED: 202,
  BAD_GATEWAY: 502,
  BAD_REQUEST: 400,
  CONFLICT: 409,
  CREATED: 201,
  FORBIDDEN: 403,
  GATEWAY_TIMEOUT: 504,
  INTERNAL_SERVER_ERROR: 500,
  NOT_FOUND: 404,
  NOT_IMPLEMENTED: 501,
  OK: 200,
  PAYMENT_REQUIRED: 402,
  PRECONDITION_FAILED: 412,
  PROXY_AUTHENTICATION_REQUIRED: 407,
  REQUEST_TOO_LONG: 413,
  REQUEST_URI_TOO_LONG: 414,
  SERVICE_UNAVAILABLE: 503,
  TOO_MANY_REQUESTS: 429,
  UNAUTHORIZED: 401,
  UNPROCESSABLE_ENTITY: 422,

  LOGGED_IN: ["customer", "administrator"],
  AUTH_ROLES: ["customer", "administrator"],

  DEFAULT_IMAGE: "images/placeholder.jpeg",
  STATUSES: ["active", "deactive", "blocked"],

  // Messages
  RECORD_CREATED: "Record created successfully!",
  ACCESS_DENIED_POST: "You are not allowed to post paid content!",
  SOMETHING_WENT_WONG: "Opps Something wents wrong..! please try agian!",
  WEATHER_DETAILS: "Weather details..!",
  LOGOUT: "User Logout successfully!",
  RECORD_UPDATED: "Record updated successfully!",
  RECORD_DELETED: "Record deleted successfully!",
  NO_RECORD_FOUND: "No record found for given details",
  TOKEN_EXPIRED: "Invalid Token or Your token has expired..! ",
  USER_BLOCK: "User Block Successfully..!!",
  RECORDS_FOUND: "Records found for given details",
  VALIDATION_ERROR: "Please Check your inputs! Something went Wrong.",
  INVALID_CREDENTIALS: "Invalid Credentials, Please check and try again!",
  EMAIL_EXIST: "Usename is already in use by another account",
  EMAIL_NOT_FOUND: "Username is not registered.",
  USER_NOT_FOUND: "User is not registered.",
  INVALID_FILE_TYPE: "File type not supported.",
  ENOT_ACCESS: "Unable to create directory.",
  SUCCESS: 1,
  FAIL: 0,

};
